#!/bin/sh

#
# chkconfig: 35 98 98
# description: Node.js server and benchmark tools initialization
#

. /etc/rc.d/init.d/functions

USER="totec2014"
DAEMON="/usr/bin/node"

SERVER_ROOT_DIR="/home/$USER/yamamoto-akihiro"

SERVER="$SERVER_ROOT_DIR/app.js"

LOCK_FILE="/var/lock/subsys/node-server"

do_start()
{
        if [ ! -f "$LOCK_FILE" ] ; then
                echo -n $"Starting $SERVER: "
                cd $SERVER_ROOT_DIR && $DAEMON $SERVER &
                RETVAL=$?
                echo
                [ $RETVAL -eq 0 ] && touch $LOCK_FILE
        else
                echo "$SERVER is locked."
                RETVAL=1
        fi
}
do_stop()
{
        echo -n $"Stopping $SERVER: "
        pid_server=`ps -aefw | grep "$DAEMON $SERVER" | grep -v " grep " | awk '{print $2}'`
        kill -9 $pid_server > /dev/null 2>&1 && echo_success || echo_failure
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && rm -f $LOCK_FILE
}

case "$1" in
        start)
                do_start
                ;;
        stop)
                do_stop
                ;;
        restart)
                do_stop
                do_start
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                RETVAL=1
esac

exit $RETVAL